language: java

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6

install:
  - "./gradlew assemble"

script:
  - "./gradlew :verify"

jdk:
  - oraclejdk8

notifications:
  email: false